[project]
name = "carpark-availabilities-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "boto3>=1.43.75",
    "mypy>=2.2.0",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.20",
    "tzdata>=2026.3",
]

[tool.pytest.ini_options]
pythonpath = ["."]
