"""S3 and Athena integration for querying Gold marts and publishing edge-ready JSON files."""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
import csv
from datetime import datetime, timezone
import io
import json
import logging
import os
import time
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse

import boto3

from datamart.exporter import (
    build_carpark_documents,
    create_summary_bundle_gzip,
    dump_carpark_document_json,
)
from datamart.schema import DATAMART_API_VERSION

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# Numerical columns expected from mart_carpark_day_of_week_distribution
FLOAT_COLUMNS = {
    "lots_avail_min",
    "lots_avail_p10",
    "lots_avail_p25",
    "lots_avail_median",
    "lots_avail_p75",
    "lots_avail_p90",
    "lots_avail_max",
    "lots_avail_mean",
    "lots_avail_stddev",
    "lots_occ_min",
    "lots_occ_p10",
    "lots_occ_p25",
    "lots_occ_median",
    "lots_occ_p75",
    "lots_occ_p90",
    "lots_occ_max",
    "lots_occ_mean",
    "lots_occ_stddev",
    "occupancy_min",
    "occupancy_p10",
    "occupancy_p25",
    "occupancy_median",
    "occupancy_p75",
    "occupancy_p90",
    "occupancy_max",
    "occupancy_mean",
    "occupancy_stddev",
    "probability_full",
    "probability_high_occupancy",
    "location_latitude",
    "location_longitude",
}

INT_COLUMNS = {
    "day_of_week",
    "hour_of_day_sgt",
    "observation_count",
    "total_lots",
}

BOOL_COLUMNS = {
    "is_weekend",
    "has_capacity_data",
}


def _parse_s3_url(s3_url: str) -> tuple[str, str]:
    """Extracts bucket and key prefix from an s3:// URI."""
    parsed = urlparse(s3_url)
    bucket = parsed.netloc
    key = parsed.path.lstrip("/")
    return bucket, key


def run_athena_query(
    query: str,
    database: str,
    s3_staging_dir: str,
    workgroup: str = "primary",
    athena_client: Optional[Any] = None,
    poll_interval_sec: float = 2.0,
    max_timeout_sec: float = 600.0,
) -> str:
    """Submits an Athena SQL query and blocks until completion."""
    client = athena_client or boto3.client("athena")

    logger.info(f"Submitting Athena query against database '{database}'...")
    response = client.start_query_execution(
        QueryString=query,
        QueryExecutionContext={"Database": database},
        ResultConfiguration={"OutputLocation": s3_staging_dir},
        WorkGroup=workgroup,
    )
    query_execution_id = response["QueryExecutionId"]
    logger.info(f"Athena query submitted. QueryExecutionId: {query_execution_id}")

    start_time = time.time()
    while True:
        elapsed = time.time() - start_time
        if elapsed > max_timeout_sec:
            raise TimeoutError(
                f"Athena query {query_execution_id} timed out after {max_timeout_sec}s."
            )

        status_response = client.get_query_execution(
            QueryExecutionId=query_execution_id
        )
        state = status_response["QueryExecution"]["Status"]["State"]

        if state == "SUCCEEDED":
            logger.info(
                f"Athena query {query_execution_id} completed successfully in {elapsed:.1f}s."
            )
            return query_execution_id
        elif state in ("FAILED", "CANCELLED"):
            reason = status_response["QueryExecution"]["Status"].get(
                "StateChangeReason", "Unknown reason"
            )
            raise RuntimeError(f"Athena query {query_execution_id} {state}: {reason}")

        time.sleep(poll_interval_sec)


def fetch_query_results_from_s3(
    query_execution_id: str,
    s3_staging_dir: str,
    s3_client: Optional[Any] = None,
) -> List[Dict[str, Any]]:
    """Streams and parses the raw CSV output generated by Athena directly from S3."""
    client = s3_client or boto3.client("s3")
    staging_bucket, staging_prefix = _parse_s3_url(s3_staging_dir)
    csv_key = f"{staging_prefix.rstrip('/')}/{query_execution_id}.csv"

    logger.info(
        f"Downloading Athena result CSV from s3://{staging_bucket}/{csv_key}..."
    )
    response = client.get_object(Bucket=staging_bucket, Key=csv_key)
    csv_stream = io.StringIO(response["Body"].read().decode("utf-8"))

    reader = csv.DictReader(csv_stream)
    records: List[Dict[str, Any]] = []

    for row in reader:
        typed_row: Dict[str, Any] = {}
        for col, val in row.items():
            if val is None or val == "" or val.lower() == "null":
                typed_row[col] = None
            elif col in FLOAT_COLUMNS:
                try:
                    typed_row[col] = float(val)
                except ValueError:
                    typed_row[col] = None
            elif col in INT_COLUMNS:
                try:
                    typed_row[col] = int(val)
                except ValueError:
                    typed_row[col] = None
            elif col in BOOL_COLUMNS:
                typed_row[col] = val.lower() in ("true", "1", "t")
            else:
                typed_row[col] = val
        records.append(typed_row)

    logger.info(f"Loaded and type-cast {len(records)} rows from Athena CSV output.")
    return records


def _upload_single_carpark_json(
    s3_client: Any,
    s3_bucket: str,
    s3_key: str,
    json_str: str,
) -> None:
    """Uploads a single carpark JSON file to S3 with cache-control headers."""
    s3_client.put_object(
        Bucket=s3_bucket,
        Key=s3_key,
        Body=json_str.encode("utf-8"),
        ContentType="application/json",
        CacheControl="public, max-age=86400",
    )


def publish_datamart_to_s3(
    s3_bucket: str,
    database: Optional[str] = None,
    table_name: str = "mart_carpark_day_of_week_distribution",
    version: str = DATAMART_API_VERSION,
    s3_staging_dir: Optional[str] = None,
    max_workers: int = 20,
    s3_client: Optional[Any] = None,
    athena_client: Optional[Any] = None,
) -> Dict[str, Any]:
    """Queries the Gold distribution mart from Athena and publishes JSON files and GZIP bundles to S3."""
    client_s3 = s3_client or boto3.client("s3")
    client_athena = athena_client or boto3.client("athena")

    if database is None:
        env = os.environ.get("ENV", "prod").lower()
        database = f"{env}_marts" if env not in ("prod", "production") else "prod_marts"

    if s3_staging_dir is None:
        s3_staging_dir = f"s3://{s3_bucket}/athena-query-results/"

    query = f"""
    SELECT *
    FROM {database}.{table_name}
    ORDER BY carpark_id, lot_type, day_of_week, hour_of_day_sgt
    """

    logger.info(f"Starting datamart publication for database '{database}'...")
    query_id = run_athena_query(
        query=query,
        database=database,
        s3_staging_dir=s3_staging_dir,
        athena_client=client_athena,
    )

    rows = fetch_query_results_from_s3(
        query_execution_id=query_id,
        s3_staging_dir=s3_staging_dir,
        s3_client=client_s3,
    )

    if not rows:
        logger.warning(
            f"No rows found in mart table '{database}.{table_name}'. Aborting export."
        )
        return {
            "status": "SKIPPED",
            "reason": "Empty dataset",
            "carparks_exported": 0,
        }

    now_iso = datetime.now(timezone.utc).isoformat()
    documents = build_carpark_documents(rows, generated_at=now_iso)
    total_carparks = len(documents)
    logger.info(f"Transformed {total_carparks} distinct carpark documents.")

    prefix = f"level=datamart/version={version}"
    uploaded_count = 0

    # 1. Parallel upload of individual carpark JSON documents
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {}
        for doc in documents:
            key_id = f"{doc.carpark.carpark_id}_{doc.carpark.lot_type}"
            s3_key = f"{prefix}/carparks/{key_id}.json"
            json_str = dump_carpark_document_json(doc)
            future = executor.submit(
                _upload_single_carpark_json,
                client_s3,
                s3_bucket,
                s3_key,
                json_str,
            )
            futures[future] = s3_key

        for future in as_completed(futures):
            future.result()
            uploaded_count += 1

    # 2. Upload consolidated GZIP bundle
    bundle_key = f"{prefix}/summary/weekly_carpark_distributions.json.gz"
    bundle_bytes = create_summary_bundle_gzip(documents, generated_at=now_iso)
    client_s3.put_object(
        Bucket=s3_bucket,
        Key=bundle_key,
        Body=bundle_bytes,
        ContentType="application/json",
        ContentEncoding="gzip",
        CacheControl="public, max-age=86400",
    )
    logger.info(
        f"Uploaded compressed summary bundle to s3://{s3_bucket}/{bundle_key} ({len(bundle_bytes)} bytes)."
    )

    # 3. Upload metadata manifest
    manifest_key = f"{prefix}/manifest.json"
    manifest_data = {
        "version": version,
        "generated_at": now_iso,
        "total_carparks": total_carparks,
        "endpoints": {
            "carpark_template": f"/{prefix}/carparks/{{carpark_id}}_{{lot_type}}.json",
            "summary_bundle_gz": f"/{prefix}/summary/weekly_carpark_distributions.json.gz",
        },
        "carparks": [
            {
                "carpark_id": doc.carpark.carpark_id,
                "lot_type": doc.carpark.lot_type,
                "agency": doc.carpark.agency,
                "development": doc.carpark.development,
                "has_capacity_data": doc.carpark.has_capacity_data,
                "file_path": f"carparks/{doc.carpark.carpark_id}_{doc.carpark.lot_type}.json",
            }
            for doc in documents
        ],
    }
    client_s3.put_object(
        Bucket=s3_bucket,
        Key=manifest_key,
        Body=json.dumps(manifest_data, indent=2).encode("utf-8"),
        ContentType="application/json",
        CacheControl="public, max-age=86400",
    )
    logger.info(f"Uploaded datamart manifest to s3://{s3_bucket}/{manifest_key}.")

    return {
        "status": "SUCCESS",
        "carparks_exported": uploaded_count,
        "s3_prefix": prefix,
        "summary_bundle_bytes": len(bundle_bytes),
        "manifest_key": manifest_key,
    }
